language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.2"
    - SHOPWARE_VERSION="5.3"
  global:
    - PLUGIN_NAME=ShyimProfiler
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

cache:
   directories:
     - ${HOME}/.composer/cache/files

install:
  - composer install

before_script:
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
  - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - mv ${TRAVIS_BUILD_DIR} ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
  - php ${HOME}/shopware/bin/console sw:plugin:refresh
  - php ${HOME}/shopware/bin/console sw:plugin:install ${PLUGIN_NAME}
  - php ${HOME}/shopware/bin/console sw:plugin:activate ${PLUGIN_NAME}
  - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

script:
  - composer test

matrix:
  allow_failures:
    - env: SHOPWARE_VERSION="5.3"
    - php: nightly