language: php

addons:
    apt:
        packages:
            - ant


php:
  - 7.2
  - 7.3

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.6"
  global:
    - PLUGIN_NAME=FroshProfiler
    - SHOPWARE_DIRECTORY="${HOME}/shopware"
    - PLUGIN_DIRECTORY="${SHOPWARE_DIRECTORY}/custom/plugins"

cache:
   directories:
     - ${HOME}/.composer/cache/files

install:
  - composer install

before_script:
  - mysql -e 'CREATE DATABASE shopware;'
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
  - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - mv ${TRAVIS_BUILD_DIR} ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
  - php ${HOME}/shopware/bin/console sw:plugin:refresh
  - php ${HOME}/shopware/bin/console sw:plugin:install ${PLUGIN_NAME}
  - php ${HOME}/shopware/bin/console sw:plugin:activate ${PLUGIN_NAME}
  - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

script:
  - composer test
  - composer test-unit

after_success:
  - ./build.sh $TRAVIS_TAG

stages:
#  - name: Sonarqube
#    if: branch = master
  - test
  - name: Store-Check
    if: branch = master
  - name: Store-Sync
    if: branch = master
  - name: Store-Deploy
    if: tag IS present

jobs:
    include:
#      - stage: Sonarqube
#        language: java
#        dist: trusty
#        addons:
#          sonarcloud:
#            organization: friendsofshopware
#            token:
#              secure: "XFsTy0yoSXdc4IEJvHOf2nxqRV2YEWGfo05cRxpHUVCeVKtSvYi+Vxrl3pLHscPEcI8ytbHlEcJnCqtz3LcvWvsCLk1hjQip78hFHP05SdGGun+vC8/TSnfP2RPaJ11AH3QRxNgLE9T/uc15KJZSx7qVVFgV6CQi3IVfrhEZBYHq+FuuHOyuP2F2bnC10voXG622K1RBvuueSeaVQKFA3m4qeLAadbxhWLt84uP0yqIl/+3C4DHPBrto6MDtaW8Kae6rE+O8HjIosMSkKDSwbFAYFDtopnsf/nUjGI/bsmddXbNM2PVqhILMl9HAL6ZwdKXnbtA3tTslqjEPMyvQ4W7HvGNFlYjSfEa7z/RFSCPlD/ZQj6C7l0CrSwihMqws0LspsGqwpcan4z9lmgBZ/Fd7wd6UnmjoZ8qN7AkNteXNnOcf4CNZ/Cd/0NWFq32Cq+qKzmVYmHOActiEjYzPHFX/MFr8n5PtiJIZuXi+GsXyLZBO3j+JxV5SvpWJEQQ8605WPy1TOiyYXPxH88T+HRrZ3i4QUP9KTJTP44lrV21w8RPx//VXEEIblro2DSDxfstA2ey5/xkOYhSLwTe0qxRA2YhqMb9j5kaSh681o2se6vr3xtHoxg8P+5XnBn0FLqu0zkXN1yJIAqUkxps/KQiUqfrqqLiz78yv+Nm0soY="
#        script:
#          - sonar-scanner
#        cache:
#          directories:
#            - '$HOME/.sonar/cache'
      - stage: Store-Check
        php: 7.3
        before_script: skip
        install:
        - ./build.sh master
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.1/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
        script:
        - php frosh-plugin-upload.phar plugin:validate ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip
      - stage: Store-Sync
        before_script: skip
        php: 7.3
        install:
          - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.1/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
        script:
          - php frosh-plugin-upload.phar plugin:update ${TRAVIS_BUILD_DIR}/Resources/store
      - stage: Store-Deploy
        before_script: skip
        php: 7.3
        install:
          - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.1/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
        script:
          - ./build.sh
          - php frosh-plugin-upload.phar plugin:upload ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: MeucPO3N0fd0DNM12uYUEkwkDkMl58fCFI3t0T9k+z/34GkypQ6qOEfx8ZFAwKtpUpQC+iTvqsIMhRhEoQlI7AtTvIgETIhWIVwtT+TPf+N0BlRr0UhxN0IXdra2d7TrRPxWIYXW5CYdWkptu4kf1fpT+hvKMwUbcJsbRY6DOnPnxRDTeo2VcYzRhpM+44dQXz9UoD1/2GQBXOXieSZb2g4YGnBumVTxt4yR8omiQCuE7S0DXmI9HIDtjSbzREUdxkuO3hpA2t7QX1K5L0OJfJWjttH27jeg9snSijVWuesaIgdIyWUMtt7I2W4CbrH7wh97n/iTx4tyARF12jLqc5qw1jFw9mIwP/dVaM8+CbjhT7+Y937E2bEYnoqJkgaXvJan92SqfnsyOwE2k/LX8TASxpx1QrYPab0kI/xjoBol+TLDxTlx7ruWNStve0CDARfaaL/GK8FJxHPB/e7xIkR4gWBR2Rm4tHP61t8/Wczv7Jgp+Vx19vU2M6lG8Wi8zrj3xTF60v3zOMwJ/9IGcHR6G9zSdj1TMTkqL69+ZzY+KbLTKr3/zxwUZdOMTyN+PgLT/pSy5Sr4287/xD+La5MfFGU2tNntv8JTlg8qO+mCGLW8Cg/DWOtURL9R3AC5hjibr1QD7gHUxmeAQTDExSbuhrMr0VU+cV4EL0uInYI=
    file_glob: true
    file: FroshProfiler*.zip
    on:
      tags: true
